### ISSUE TITLE
There is an issue regarding your last round when calculating

### ISSUE THREAD

**Issue by vsseetamraju** [PingryPython-2017/red-team-sum-digits#1]
When I run the program an error message shows up:

Traceback (most recent call last):
  File "sumDigits.py", line 12, in <module>
    print(sumDigits(999))
  File "sumDigits.py", line 10, in sumDigits
    return digit + sumDigits(newNumber)
  File "sumDigits.py", line 10, in sumDigits
    return digit + sumDigits(newNumber)
  File "sumDigits.py", line 6, in sumDigits
    newNumber = int(word[1:])
ValueError: invalid literal for int() with base 10: ''

We inferred there is a problem when the recursion gets to the last round. So maybe the issue is with your terminating case

**Comment by dilanbhat** [comment]
Adding on to this, it returns the error when it recurses down to the terminating case, an empty string. Maybe you have to make the terminating case when there is still one digit left.
